/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        brand: "#6366f1",
        primary: "#a93200",
        "primary-container": "#d1430a",
        "primary-fixed": "#ffdbd0",
        "primary-fixed-dim": "#ffb59e",
        "inverse-primary": "#ffb59e",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#3a0b00",
        "on-primary-fixed-variant": "#842500",
        "on-primary-container": "#fffbff",
        secondary: "#635d5a",
        "secondary-container": "#e6ded9",
        "secondary-fixed": "#e9e1dc",
        "secondary-fixed-dim": "#cdc5c0",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#1e1b18",
        "on-secondary-fixed-variant": "#4b4642",
        "on-secondary-container": "#67625e",
        tertiary: "#615b56",
        "tertiary-container": "#7a736f",
        "tertiary-fixed": "#eae1db",
        "tertiary-fixed-dim": "#cdc5bf",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#1f1b17",
        "on-tertiary-fixed-variant": "#4b4542",
        "on-tertiary-container": "#fffbff",
        background: "#f8f9fa",
        surface: "#f8f9fa",
        "surface-variant": "#e1e3e4",
        "surface-bright": "#f8f9fa",
        "surface-dim": "#d9dadb",
        "surface-tint": "#ad3300",
        "surface-container": "#edeeef",
        "surface-container-low": "#f3f4f5",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e7e8e9",
        "surface-container-highest": "#e1e3e4",
        "on-background": "#191c1d",
        "on-surface": "#191c1d",
        "on-surface-variant": "#5a4139",
        "inverse-surface": "#2e3132",
        "inverse-on-surface": "#f0f1f2",
        outline: "#8e7067",
        "outline-variant": "#e2bfb4",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ["Manrope", "sans-serif"],
        headline: ["Manrope", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
    },
  },
  plugins: [],
};
