"""add goals

Revision ID: 21c7555d70cc
Revises: 89a8e1a8fdf2
Create Date: 2026-04-26 00:35:49.835174

"""
from alembic import op
import sqlalchemy as sa


revision = '21c7555d70cc'
down_revision = '89a8e1a8fdf2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal_completions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goal_completions_conversation_id'), 'goal_completions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_goal_completions_goal_id'), 'goal_completions', ['goal_id'], unique=False)
    op.create_index(op.f('ix_goal_completions_tenant_id'), 'goal_completions', ['tenant_id'], unique=False)
    op.create_table('goal_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('goal_type', sa.Enum('keyword', 'url_match', 'event', name='goaltype'), nullable=False),
    sa.Column('target_value', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goal_configs_tenant_id'), 'goal_configs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_goal_configs_tenant_id'), table_name='goal_configs')
    op.drop_table('goal_configs')
    op.drop_index(op.f('ix_goal_completions_tenant_id'), table_name='goal_completions')
    op.drop_index(op.f('ix_goal_completions_goal_id'), table_name='goal_completions')
    op.drop_index(op.f('ix_goal_completions_conversation_id'), table_name='goal_completions')
    op.drop_table('goal_completions')
    # ### end Alembic commands ###
