"""add ai model selection

Revision ID: 2c062beea1d0
Revises: 9eddebfc68f3
Create Date: 2026-04-26 01:09:08.797323

"""
from alembic import op
import sqlalchemy as sa


revision = '2c062beea1d0'
down_revision = '9eddebfc68f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('widget_configs', sa.Column('ai_provider', sa.String(length=50), server_default='openai', nullable=False))
    op.add_column('widget_configs', sa.Column('ai_model', sa.String(length=100), server_default='gpt-4o-mini', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('widget_configs', 'ai_model')
    op.drop_column('widget_configs', 'ai_provider')
    # ### end Alembic commands ###
