"""add conversation tags

Revision ID: 347fa6a928fc
Revises: 89d997170a09
Create Date: 2026-04-26 01:20:03.052244

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '347fa6a928fc'
down_revision = '89d997170a09'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('web_conversations', sa.Column('tags', postgresql.ARRAY(sa.String(length=50)), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('web_conversations', 'tags')
    # ### end Alembic commands ###
