"""add email follow-up

Revision ID: 7088afa005dd
Revises: 2c062beea1d0
Create Date: 2026-04-26 01:13:38.827626

"""
from alembic import op
import sqlalchemy as sa


revision = '7088afa005dd'
down_revision = '2c062beea1d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('widget_configs', sa.Column('email_followup_enabled', sa.BOOLEAN(), server_default='true', nullable=False))
    op.add_column('widget_configs', sa.Column('email_followup_subject', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('widget_configs', 'email_followup_subject')
    op.drop_column('widget_configs', 'email_followup_enabled')
    # ### end Alembic commands ###
