"""add attachment url

Revision ID: 89a8e1a8fdf2
Revises: db5d2810c8fa
Create Date: 2026-04-26 00:29:03.784070

"""
from alembic import op
import sqlalchemy as sa


revision = '89a8e1a8fdf2'
down_revision = 'db5d2810c8fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('web_messages', sa.Column('attachment_url', sa.String(length=1024), nullable=True))
    op.add_column('widget_configs', sa.Column('default_language', sa.String(length=10), server_default='en', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('widget_configs', 'default_language')
    op.drop_column('web_messages', 'attachment_url')
    # ### end Alembic commands ###
