"""add widget theme

Revision ID: 89d997170a09
Revises: 7088afa005dd
Create Date: 2026-04-26 01:17:27.398184

"""
from alembic import op
import sqlalchemy as sa


revision = '89d997170a09'
down_revision = '7088afa005dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('widget_configs', sa.Column('theme', sa.String(length=20), server_default='light', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('widget_configs', 'theme')
    # ### end Alembic commands ###
