"""add calendly url

Revision ID: b5a5c59c1aa3
Revises: 21c7555d70cc
Create Date: 2026-04-26 00:44:56.169421

"""
from alembic import op
import sqlalchemy as sa


revision = 'b5a5c59c1aa3'
down_revision = '21c7555d70cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('widget_configs', sa.Column('calendly_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('widget_configs', 'calendly_url')
    # ### end Alembic commands ###
