"""add proactive triggers

Revision ID: c5336426eeee
Revises: b5a5c59c1aa3
Create Date: 2026-04-26 00:50:42.313046

"""
from alembic import op
import sqlalchemy as sa


revision = 'c5336426eeee'
down_revision = 'b5a5c59c1aa3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('widget_configs', sa.Column('proactive_message', sa.String(length=255), nullable=True))
    op.add_column('widget_configs', sa.Column('proactive_delay', sa.INTEGER(), nullable=True))
    op.add_column('widget_configs', sa.Column('proactive_exit_intent', sa.BOOLEAN(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('widget_configs', 'proactive_exit_intent')
    op.drop_column('widget_configs', 'proactive_delay')
    op.drop_column('widget_configs', 'proactive_message')
    # ### end Alembic commands ###
