"""add_missing_lead_capture_fields

Revision ID: ccac4f4b5697
Revises: p1q2r3s4t5u6
Create Date: 2026-05-10 17:37:14.696465

"""
from alembic import op
import sqlalchemy as sa


revision = 'ccac4f4b5697'
down_revision = 'p1q2r3s4t5u6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_capture_configs', sa.Column('collect_company', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###
    op.add_column('lead_capture_configs', sa.Column('collect_job_title', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('lead_capture_configs', sa.Column('display_style', sa.String(), nullable=False, server_default='inline'))
    op.add_column('lead_capture_configs', sa.Column('collect_timing', sa.String(), nullable=False, server_default='after_specific_message'))
    op.add_column('lead_capture_configs', sa.Column('required_field_label', sa.String(), nullable=False, server_default='* Required'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead_capture_configs', 'required_field_label')
    op.drop_column('lead_capture_configs', 'collect_timing')
    op.drop_column('lead_capture_configs', 'display_style')
    op.drop_column('lead_capture_configs', 'collect_job_title')
    op.drop_column('lead_capture_configs', 'collect_company')
    # ### end Alembic commands ###
