"""add zapier webhook url

Revision ID: db5d2810c8fa
Revises: n9o0p1q2r3s4
Create Date: 2026-04-26 00:14:54.872083

"""
from alembic import op
import sqlalchemy as sa


revision = 'db5d2810c8fa'
down_revision = 'n9o0p1q2r3s4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('zapier_webhook_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'zapier_webhook_url')
    # ### end Alembic commands ###
