"""Add suggested questions

Revision ID: f5149e09613e
Revises: h3i4j5k6l7m8
Create Date: 2026-04-14 18:52:22.108314

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'f5149e09613e'
down_revision = 'h3i4j5k6l7m8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('widget_configs', sa.Column('suggested_questions', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('widget_configs', 'suggested_questions')
    # ### end Alembic commands ###
